"""is delete column added into user

Revision ID: e3cd8aa624e5
Revises: 3d18f6b55510
Create Date: 2021-06-08 11:25:23.527314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3cd8aa624e5'
down_revision = '3d18f6b55510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'emailhandler', ['id'])
    op.add_column('users', sa.Column('is_delete', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_delete')
    op.drop_constraint(None, 'emailhandler', type_='unique')
    # ### end Alembic commands ###
